name: ai_voice_agent
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  path_provider: ^2.0.1
  audioplayers: ^6.1.0
  web: ">=0.5.1 <2.0.0"
  record: ^5.2.0
  intl: ^0.20.2
  http: ^0.13.6
  universal_html: ^2.2.4
  http_parser: ^4.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
